config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :sessions, only: %i[new create destroy]

  resources :users do
    resource :basket, only: %i[show] do
      post :add_product
    end

    resources :basket, only: %i[update destroy], controller: :baskets, as: :basket_items

    resources :orders, only: %i[create show destroy], shallow: true do
      collection do
        get :index, constraints: ->(req) { req.format == :html }
        post :index, action: :xml_index, constraints: ->(req) { req.format == :xml }
      end
      member do
        get :pay
        get :confirm_payment
        get :confirm
        post :confirm_shipment
        post :confirm_receipt
      end
    end

    member do
      get :picture, action: :show_picture
    end
  end

  resources :products

  namespace :management do
    resources :messages, only: %i[index create destroy]
  end

  get '/contacts', to: 'contacts#index'
  get '/oauth', to: 'oauth#code'
  post '/oauth', to: 'oauth#token'
  post '/set_language/:lang', to: 'welcome#set_language', as: :set_language
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_reader :password
  attr_accessor :password_confirmation

  has_many :basketed, class_name: 'Basket', dependent: :destroy
  has_many :orders, dependent: :destroy

  def password=(new_password)
    self[:encrypted_password] = Digest::MD5.hexdigest(new_password)
  end

  def country_name
    ISO3166::Country.new(country_code)&.name
  end

  def display_name
    full_name || email
  end

  def admin?
    admin
  end

  def picture_path
    "/uploads/users/#{id}/#{picture}" if picture.present?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_login, except: %i[show new create show_picture]
  before_action :set_user, only: %i[show edit update destroy show_picture]

  # GET /users or /users.json
  def index
    @users = policy_scope User
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User::CreateUser.instance.call(params: params.require(:user))

    respond_to do |format|
      if @user.persisted?
        format.html { redirect_to @user, flash: { success: 'User was successfully created.' } }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    @user = User::UpdateUser.new(
      target: @user,
      actor: current_user
    ).call(params: params.require(:user))

    if @user.errors.empty?
      if session[:return_to_order].present?
        session[:address_confirmed] = true

        redirect_to pay_order_path(session[:return_to_order]), notice: 'User address was successfully confirmed.'

        session.delete(:return_to_order)
      else
        redirect_to @user, flash: { success: 'User was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    authorize @user

    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, flash: { success: 'User was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  def show_picture
    show_empty_image and return if params[:name].nil?

    file_name = File.basename params[:name]
    file_path = Rails.root.join "public/uploads/users/#{@user.id}/#{file_name}"
    show_empty_image and return unless File.exist?(file_path)

    file_type = MimeMagic.by_magic(File.open(file_path)) || 'application/octet-stream'

    send_file file_path, type: file_type, disposition: 'inline'
  end

  private

  def show_empty_image
    redirect_to helpers.asset_pack_path('media/images/No_image_available.svg')
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  - unless @user.persisted?
    fieldset
      legend Authentication data
      = f.input :email
      = f.input :password
      = f.input :password_confirmation

  fieldset
    legend Profile data
    = f.input :picture, as: :file
    = f.input :full_name
    = f.input :address
    = f.input :city
    = f.input :country_code
    = f.input :locked if policy(@user).update_locked?

  .actions = f.button :submit, class: 'btn-primary'

app/views/users/edit.html.slim
main.container
  h1 Editing user

  == render 'form'

  - unless session[:return_to_order].present?
    => link_to 'Show', @user
    '|
    - if policy(User).index?
      =< link_to 'Back', users_path
    - else
      =< link_to 'Back', root_path

app/views/users/index.html.slim
.container
  h1 Listing users

  table.table.table-striped
    thead
      tr
        th[ scope = "col" ] Email
        th[ scope = "col" ] Name
        th[ scope = "col" ] Country
        th[ scope = "col" ] Registered at
        th[ scope = "col" ] Actions

    tbody
      - @users.each do |user|
        tr [ class = "#{'table-danger' if user.locked?}" ]
          td = link_to user.email, user
          td = link_to user.full_name, user
          td = user.country_name
          td = l user.created_at
          td
            - if policy(user).edit?
              => link_to 'Edit', edit_user_path(user)
            - if policy(user).destroy?
              => link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

  br

  = link_to 'New User', new_user_path

app/views/users/new.html.slim
main.container
  h1 New user

  == render 'form'

  - if policy(User).index?
    =< link_to 'Back', users_path
  - else
    =< link_to 'Back', root_path

app/views/users/show.html.slim
main.container
  h1 User profile for #{@user.display_name}

  .row
    .col-md-6.col-lg-4
      = image_tag picture_user_path(@user, name: @user.picture), class: 'img-fluid'
    .col-md-6.col-lg-8
      table.table.table-striped
        tbody
          tr
            th[ scope = "row" ] Email
            td = @user.email
          tr
            th[ scope = "row" ] Name
            td = @user.full_name
          tr
            th[ scope = "row" ] Country
            td = @user.country_name
          tr
            th[ scope = "row" ] City
            td = @user.city
          tr
            th[ scope = "row" ] Address
            td = @user.address
          tr
            th[ scope = "row" ] Registered at
            td = l @user.created_at

  - if policy(@user).edit?
    => link_to 'Edit', edit_user_path(@user)
    '|
  - if policy(@user).show_basket?
    => link_to 'Basket', user_basket_path(@user)
    '|
  - if policy(User).index?
    =< link_to 'Back', users_path
  - else
    =< link_to 'Back', root_path