config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :sessions, only: %i[new create destroy]

  resources :users do
    resource :basket, only: %i[show] do
      post :add_product
    end

    resources :basket, only: %i[update destroy], controller: :baskets, as: :basket_items

    resources :orders, only: %i[create show destroy], shallow: true do
      collection do
        get :index, constraints: ->(req) { req.format == :html }
        post :index, action: :xml_index, constraints: ->(req) { req.format == :xml }
      end
      member do
        get :pay
        get :confirm_payment
        get :confirm
        post :confirm_shipment
        post :confirm_receipt
      end
    end

    member do
      get :picture, action: :show_picture
    end
  end

  resources :products

  namespace :management do
    resources :messages, only: %i[index create destroy]
  end

  get '/contacts', to: 'contacts#index'
  get '/oauth', to: 'oauth#code'
  post '/oauth', to: 'oauth#token'
  post '/set_language/:lang', to: 'welcome#set_language', as: :set_language
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :items, class_name: 'Order::Item', dependent: :destroy

  enum status: {
    new: 0,
    pending: 10,
    paid: 20,
    confirmed: 30,
    shipped: 40,
    received: 50,
    cancelled: 120,
  }, _suffix: true

  enum payment_method: {
    dummy: 10,
  }, _suffix: true, _scopes: false

  def total_cost
    if items.loaded?
      # Use item method to calculate cost
      items.sum(&:items_cost)
    else
      # Assume that we won't load all items and use SQL to calculate cost
      items.sum('price * count')
    end
  end

  def expired?
    status_before_type_cast < self.class.statuses[:paid] && created_at < 1.hour.ago
  end

  %i[paid shipped received].each do |status_type|
    status_id = statuses[status_type]

    define_method :"#{status_type}?" do
      !cancelled_status? && status_for_database >= status_id
    end
  end
end

app/models/order/item.rb
# frozen_string_literal: true

class Order
  class Item < ApplicationRecord
    belongs_to :order
    belongs_to :product

    def product_name
      product.present? ? product.name : 'Deleted product'
    end

    def items_cost
      price * count
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  include TokenAuthentication

  before_action :require_login
  before_action :set_user, only: %i[index xml_index create]
  before_action :set_order, only: %i[
    show
    pay confirm_payment
    confirm confirm_shipment confirm_receipt
    destroy
  ]

  prepend_before_action :authenticate_by_token, only: %i[xml_index]
  skip_before_action :verify_authenticity_token, only: %i[xml_index]

  # GET /orders or /orders.xml
  def index
    authorize @user, :show_orders?

    @orders = policy_scope(@user.orders).order(created_at: :desc)
  end

  def xml_index
    authorize @user, :show_orders?

    @orders = policy_scope(@user.orders).order(created_at: :desc)

    parse_request_xml if request.body.size.positive?

    @orders = @orders.includes(items: :product)
  end

  # GET /orders/1
  def show
    authorize @order

    @order_items = @order.items.includes(:product)
  end

  # POST /orders
  def create
    authorize @user, :order?

    @order = Order::CreateOrder.instance.call(user: current_user)

    if @order
      redirect_to @order, notice: 'Order was successfully created.'
    else
      redirect_to user_basket_path(@user), alert: 'Cannot create order.'
    end
  end

  def pay
    authorize @order

    @order.pending_status!

    unless session[:address_confirmed] # rubocop:disable Style/GuardClause
      session[:return_to_order] = @order.id
      redirect_to edit_user_path(@order.user), notice: 'Please confirm user name and address:' and return
    end
  end

  def confirm_payment
    authorize @order

    if Order::ConfirmPayment.instance.call(
      order: @order,
      method: params[:payment_method],
      key: params[:confirmation_key]
    )
      redirect_to confirm_order_path(@order)
    else
      redirect_to @order, alert: 'Payment confirmation failed'
    end
  end

  def confirm
    authorize @order

    if @order.confirmed_status!
      redirect_to @order, notice: 'Order confirmed'
    else
      redirect_to @order, alert: 'Cannot confirm this order'
    end
  end

  def confirm_shipment
    authorize @order

    if Order::ConfirmShipment.instance.call(order: @order)
      redirect_to @order, notice: 'Order successfully marked as shipped'
    else
      redirect_to @order, alert: 'Cannot update order status'
    end
  end

  def confirm_receipt
    authorize @order

    if Order::ConfirmReceipt.instance.call(order: @order)
      redirect_to @order, notice: 'Order successfully marked as received'
    else
      redirect_to @order, alert: 'Cannot update order status'
    end
  end

  # DELETE /orders/1
  def destroy
    authorize @order

    @order.destroy!

    redirect_to user_orders_path(@order.user_id), notice: 'Order was successfully destroyed.'
  end

  private

  def parse_request_xml
    xml_body = Nokogiri::XML(request.body) do |config|
      # noent actually means 'expand entities'
      config.strict.nonoent
    end

    @date_start = xml_body.at_css('orders>dateStart').text
    @date_end = xml_body.at_css('orders>dateEnd').text

    @orders = @orders.where('created_at > ?', @date_start) if @date_start.present?
    @orders = @orders.where('created_at < ?', @date_end) if @date_end.present?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/index.html.slim
main.container
  h1 Listing orders

  table.table.table-striped
    thead
      tr
        th[ scope = "col" ] Ordered at
        th[ scope = "col" ] Status
        th[ scope = "col" ] Total cost
        th[ scope = "col" ] Payment method
        th[ scope = "col" ] Shipped at
        th[ scope = "col" ] Received at
        th[ scope = "col" ] Actions

    tbody
      - @orders.each do |order|
        tr
          td = link_to l(order.created_at), order
          td = order.status
          / XXX: there's n+1 query issue in total_cost, should cache it in a separate column
          /      or use more complex query in a real application
          td = order.total_cost
          td = order.payment_method
          td = order.shipped_at
          td = order.received_at
          td
            - if policy(order).pay?
              => link_to 'Pay', pay_order_path(order), class: 'btn btn-primary'
            - if policy(order).confirm_shipment?
              => link_to 'Mark as shipped', confirm_shipment_order_path(order), class: 'btn btn-primary', method: :post
            - if policy(order).confirm_receipt?
              => link_to 'Mark as received', confirm_receipt_order_path(order), class: 'btn btn-success', method: :post
            - if policy(order).destroy?
              => link_to 'Delete', order_path(order), class: 'btn btn-danger', method: :delete

  br

app/views/orders/pay.html.slim
main.container
  h1 Payment

  h3 Select payment method
  .card
    h5.card-header Dummy
    .card-body
      p.card-text Pay $#{@order.total_cost} for order ##{@order.id}
    .card-footer
      = form_tag confirm_payment_order_path(@order), method: :get do
        = hidden_field_tag :payment_method, 'dummy'
        = hidden_field_tag :confirmation_key, SecureRandom.hex(16)
        = submit_tag "Pay $#{@order.total_cost}", class: 'btn btn-primary'

app/views/orders/show.html.slim
main.container
  h1 Order details
  table.table.table-striped
    tbody
      tr
        th[ scope = "row" ] Order status
        td = @order.status.humanize
      - if @order.paid?
        tr
          th[ scope = "row" ] Payment method
          td = @order.payment_method
      - if @order.shipped?
        tr
          th[ scope = "row" ] Shipped at
          td = l @order.shipped_at
      - if @order.received?
        tr
          th[ scope = "row" ] Received at
          td = l @order.received_at

  h3 Items
  table.table.table-striped
    thead
      tr
        th[ scope = "col" ] Product
        th[ scope = "col" ] Price
        th[ scope = "col" ] Count
        th[ scope = "col" ] Total cost
    tbody
      - @order_items.each do |item|
        tr
          td = link_to item.product_name, item.product
          td = sprintf "%0.2f", item.price
          td = item.count
          td = sprintf "%0.2f", item.items_cost
      tr
        th[ scope = "row" colspan = "3" ] Total
        td = sprintf "%0.2f", @order.total_cost

  - if policy(@order).pay?
    => link_to 'Pay and confirm', pay_order_path(@order), class: 'btn btn-success'
  - if policy(@order).confirm_shipment?
    => link_to 'Mark as shipped', confirm_shipment_order_path(@order), class: 'btn btn-primary', method: :post
  - if policy(@order).confirm_receipt?
    => link_to 'Mark as received', confirm_receipt_order_path(@order), class: 'btn btn-success', method: :post
  - if policy(@order).destroy?
    => link_to 'Delete', order_path(@order), class: 'btn btn-danger', method: :delete
  => link_to 'Back', user_orders_path(@order.user), class: 'btn btn-secondary'