config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :sessions, only: %i[new create destroy]

  resources :users do
    resource :basket, only: %i[show] do
      post :add_product
    end

    resources :basket, only: %i[update destroy], controller: :baskets, as: :basket_items

    resources :orders, only: %i[create show destroy], shallow: true do
      collection do
        get :index, constraints: ->(req) { req.format == :html }
        post :index, action: :xml_index, constraints: ->(req) { req.format == :xml }
      end
      member do
        get :pay
        get :confirm_payment
        get :confirm
        post :confirm_shipment
        post :confirm_receipt
      end
    end

    member do
      get :picture, action: :show_picture
    end
  end

  resources :products

  namespace :management do
    resources :messages, only: %i[index create destroy]
  end

  get '/contacts', to: 'contacts#index'
  get '/oauth', to: 'oauth#code'
  post '/oauth', to: 'oauth#token'
  post '/set_language/:lang', to: 'welcome#set_language', as: :set_language
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.slim
.container
  - flash.each do |type, message|
    .alert[ class = alert_class_for(type) ]
      = message

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-dark.bg-dark.navbar-expand-lg
  .container-fluid
    = link_to :root, class: 'navbar-brand' do
      span.text-success Vulnerable
      | App
    button[ class = "navbar-toggler"
            type = "button"
            data-bs-toggle = "collapse"
            data-bs-target = "#navbar-top"
            aria-controls = "navbar-top"
            aria-expanded = "false"
            aria-label = "Toggle navigation" ]
      span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar-top
      ul.navbar-nav.me-auto
        - if policy(User).index?
          li.nav-item
            = link_to 'Users', users_path, class: 'nav-link'

        li.nav-item
          = link_to 'Products', products_path, class: 'nav-link'
        li.nav-item
          = link_to 'Contacts', contacts_path, class: 'nav-link'

        - if policy(Management::Message).index?
          li.nav-item
            = link_to 'Messages', management_messages_path, class: 'nav-link'

      ul.navbar-nav
        li.nav-item.dropdown
          a.nav-link.dropdown-toggle[ href = "#"
                                      id = "navbar-language-menu"
                                      role = "button"
                                      data-bs-toggle = "dropdown"
                                      aria-expanded = "false" ]
            | Language
          ul.dropdown-menu.dropdown-menu-dark.dropdown-menu-end[ aria-labelledby = "navbar-language-menu" ]
            li
              = link_to 'English', set_language_path(:en), class: 'dropdown-item', method: :post
            li
              = link_to 'Russian', set_language_path(:ru), class: 'dropdown-item', method: :post

        li.nav-item.dropdown
          a.nav-link.dropdown-toggle[ href = "#"
                                      id = "navbar-user-menu"
                                      role = "button"
                                      data-bs-toggle = "dropdown"
                                      aria-expanded = "false" ]
            = logged_in? ? current_user.display_name : 'Anonymous'
          ul.dropdown-menu.dropdown-menu-dark.dropdown-menu-end[ aria-labelledby = "navbar-user-menu" ]
            - if logged_in?
              li
                = link_to 'My profile', current_user, class: 'dropdown-item'
              li
                = link_to 'My basket', user_basket_path(current_user), class: 'dropdown-item'
              li
                = link_to 'My orders', user_orders_path(current_user), class: 'dropdown-item'
              li
                hr.dropdown-divider
              li
                = link_to 'Log out', session_path(current_user.id), class: 'dropdown-item', method: :delete
            - else
              li
                = link_to 'Log in', new_session_path, class: 'dropdown-item'
              li
                = link_to 'Register', new_user_path, class: 'dropdown-item'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | VulnerableApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body[id="page-#{controller.controller_name}-#{controller.action_name}" class=controller.controller_name]
    = render partial: 'layouts/navbar'
    = render partial: 'layouts/flash'

    = yield